### ISSUE TITLE
Error: MEA.dat file is missing!

### ISSUE THREAD

**Issue by BunnyTheLifeguard** [platomav/MEAnalyzer#11]
I get this error after pointing MEA to my .rom file.

Using Manjaro Linux, ME Analyzer v1.82.3, Python 3.7.3.
Let me know if you need additional info.

Thanks in advance.

**Comment by platomav** [comment]
If you're seeing this then you don't have the MEA databases at the same folder as the script. Section C of the Readme explains this.

**Comment by BunnyTheLifeguard** [comment]
Thanks @platomav 
Copying the .dat files into the dist folder (and removing the blanks in one folder name) solved it.
Gives me a table and this one at the bottom:
`Error: Detected CSE Extension 0x03 with wrong Partition Hash at FTPR > FTPR.man!`

What's that one about?

**Comment by platomav** [comment]
It means that during CSME firmware parsing, the hash of FTPR partition was found to be wrong. If a "__CHECK__" folder got created then the firmware has some sort of corruption. Otherwise, it is a [known firmware with a bad hash](https://github.com/platomav/MEAnalyzer/blob/3700e7d8454e71b403991a05801eb34a33c70d06/MEA.py#L7070). The latter is common for CSME 11.8 Slim firmware from Apple, if that's what you loaded into MEA.

**Comment by BunnyTheLifeguard** [comment]
There is indeed a __CHECK__ folder. It's not an Apple, it's a Lenovo X1 Carbon. How can I get the hash?

**Comment by platomav** [comment]
There is nothing to get. The firmware is corrupted and you'll should see the full extend of it if you unpack it via "-unp86 -bug86". This is not a ME Analyzer issue. Instead, you need to follow the [Engine CleanUp Guide](https://www.win-raid.com/t1658f39-Guide-Clean-Dumped-Intel-Engine-CS-ME-CS-TXE-Regions-with-Data-Initialization.html) in order to fix the problem.

**Comment by BunnyTheLifeguard** [comment]
I'll check it out, thanks.

**Comment by platomav** [comment]
Alright, if you need more help fixing the corruption then post at the win-raid forum. I'll go ahead and close this issue.
