### ISSUE TITLE
Easier to parse output version

### ISSUE THREAD

**Issue by hughsie** [platomav/MEAnalyzer#14]
Hi,

I'm pondering using your project on the LVFS (https://fwupd.org/lvfs/) to analyse the ME firmware that's being uploaded by vendors such as HP, Lenovo and Dell. MEAnalyser is by far superior to the other alternatives I've researched, although I do have some concerns:

 * I can't use anything without updates via pip on the production server, so https://github.com/platomav/PTable/archive/boxchar.zip is a no-go.

* I need to be able to parse the output, preferably as JSON or XML, but even a plain `Key: Value` format would be fine too.

* Suppose without the fancy tables, colorama becomes unnecessary too.

I'm using this command like at the moment: `python3 ./MEA.py ../me_cleaner/X1-ME-firmware.bin -skip -redir` -- but I'm perfect willing to write code and submit a PR for the above requests if you're receptive to the idea. The easiest way would be to create a MEA_cli.py that imports all the things in MEA.py and then outputs as the existing tool does now and a MEA_json.py that outputs all the info as a big JSON blob. I'd be fine if MEA_json.py lived in the LVFS, and I could just import things from MEA.py directly.

Anyway, comments welcome. I didn't want to start work if the idea if you were not happy with the idea. Thanks.

**Comment by platomav** [comment]
Hello,

* MEA uses a fork of PrettyTable for the tabloid display. My fork is mainly based on [PTable](https://github.com/kxxoling/PTable), which is a fork by kxxoling. User Autoplectic then forked PTable and created the "boxchar" branch which added nicer/unicode borders but had some bugs which were fixed at my own "boxchar" fork. MEA is fully capable of working with the original PTable, which does have a pip entry over [here](https://pypi.org/project/PTable/). All you need to do is the disable the unicode borders which is exactly what the **-redir** parameter does. It was implemented due to a bug in PTable & Colorama but it does serve your purpose regardless. I could also create a pip entry for my own fork I suppose but you can also use the PTable fork with -redir if you like.

* I'm not familiar with Jason or XML but I do use some very basic functionality of the former in a few instances in MEA so that would be preferred. Outputting in JSON will _probably_ not be very difficult because I've tried over the years to gather the messages and output at the end of the code (last 100 lines approximately). I'm not sure if 100% everything is there but I believe that the main functionality (info display) is fully parsed at the end of the analysis. As for the implementation, I like things to be within the main script, unless absolutely necessary. So, for example, a hypothetical JSON code for output will be part of MEA.py which can then be called by interested 3rd-parties via a parameter.

* Colorama was there way before PTable so they're not related. Unlike PTable, Colorama can be disabled easily by removing its initialization and replacing the color values with empty string values.

**Comment by platomav** [comment]
@hughsie 

I've created a development branch of MEA, called [html_output](https://github.com/platomav/MEAnalyzer/tree/html_output), which is able to create HTML Table files for every textual output during firmware analysis or unpacking. These can be easily parsed by external tools via the table, caption, thead, tbody, tr, td etc HTML tags.

The new parameter is "-html" and works for both the main MEA output (Firmware and/or PMC and/or Messages) and the CSE unpacking output. To test it, you need to install the [fix_html](https://github.com/platomav/PTable/tree/fix_html) branch of my own PTable. I can create a pypi package for my own PTable afterwards, once everything is ready.

![Capture1](https://user-images.githubusercontent.com/11527726/60040033-c1c04000-96c0-11e9-97f8-be188370d1b9.PNG)

![Capture2](https://user-images.githubusercontent.com/11527726/60040043-c553c700-96c0-11e9-9d57-714e268123a7.PNG)

![Capture3](https://user-images.githubusercontent.com/11527726/60040048-c7b62100-96c0-11e9-90f1-3729f93437a0.PNG)

![Capture4](https://user-images.githubusercontent.com/11527726/60040060-ce449880-96c0-11e9-86d5-5801b282acc3.PNG)

**Comment by hughsie** [comment]
Although I really think this is a step in the right direction, I do think something machine-readable with a schema would be best -- e.g. xml or json. HTML isn't really designed to be consumed by other web apps.

**Comment by platomav** [comment]
@hughsie

Added JSON exporting via "-json" parameter. Test it by using the latest MEA from [html_output](https://github.com/platomav/MEAnalyzer/tree/html_output) branch and make sure to re-install the latest PTable from [fix_html](https://github.com/platomav/PTable/tree/fix_html) branch.

![Capture1](https://user-images.githubusercontent.com/11527726/60374755-af226f80-9a0e-11e9-9ce0-60e490181e82.PNG)

![Capture2](https://user-images.githubusercontent.com/11527726/60374756-afbb0600-9a0e-11e9-8d87-2a3871142e64.PNG)

![Capture3](https://user-images.githubusercontent.com/11527726/60374757-afbb0600-9a0e-11e9-8123-94aece391def.PNG)

**Comment by hughsie** [comment]
That's super, thanks. I'll give it a go on Monday.
