### ISSUE TITLE
Feature request: print additional firmware info + standalone analyze of IOM(P), TBT(P)

### ISSUE THREAD

**Issue by c0d3z3r0** [platomav/MEAnalyzer#31]
Currently, MEA lists information on CSME,PMC,PCHC,NPHY (at least on TGL, different for other platforms). IOM and TBT fw would be nice to have, too. Both are already decoded with -unp86

Being able to analyze TBT(P), IOM(P) standalone (MEA.py <file>) like the other images/binaries/partitions would be awesome, too! :-)

btw. what about adding these images to the firmware repo?

**Comment by platomav** [comment]
MEA supports in-depth analysis and info display only for IUPs which are mandatory for CSE/GSC FWUpdate operations. Currently, that means PMC, PCHC, PHY and OROM. The same applies to the community assisted firmware repositories.

Intel has many IUPs for different functions and platforms with many variations between them based on generation, revisions etc. It is neither practical nor needed to add in-depth analysis for everything, so only what's absolutely necessary is supported.

As you mentioned, you can always fully unpack any given CSE/GSC firmware and retrieve any relevant IUP info and files that way. Since there are no plans to deviate from the aforementioned plan currently, I'll go ahead and close this request/issue.
